### ISSUE TITLE
[QC][Local] Crash full node when call RPC "retrieveblockbyheight"

### ISSUE THREAD

**Issue by Hangntt15** [incognitochain/incognito-chain#1137]
**Environment:**
```
Revision: 3463f8f99525833490a353dde50c24d2234fb3ff
Branch: origin/development
Highway: cdfae422c33ce5fb69670e22e6b578a40fa7ce3c/ testnet_bcfn_libp2p_20201018_02
```
**RPC called:**
```
{
   "jsonrpc": "1.0",
   "id": 1,
   "method": "retrieveblockbyheight",
   "params": [
      3760,
      4,
      "1"
   ]
}
```
**Full node log**
```
2021-01-08 10:49:18.936 shardprocess.go:184 [INF] BlockChain log: SHARD 0 | Update Beacon Instruction, block height 3760 with hash e24f9c4f7d9fec96bdd4090c7520f45674cc9919b9e0a56cffdcd6941d7aa4b1 

2021-01-08 10:49:18.936 shardprocess.go:189 [INF] BlockChain log: SHARD 0 | Store New Shard Block And Update Data, block height 3760 with hash e24f9c4f7d9fec96bdd4090c7520f45674cc9919b9e0a56cffdcd6941d7aa4b1 

2021-01-08 10:49:18.936 shardprocess.go:1024 [INF] BlockChain log: SHARD 0 | Process store block height 3760 at hash e24f9c4f7d9fec96bdd4090c7520f45674cc9919b9e0a56cffdcd6941d7aa4b1
2021-01-08 10:49:18.937 shardprocess.go:1045 [DBG] BlockChain log: Transaction in block with hash e24f9c4f7d9fec96bdd4090c7520f45674cc9919b9e0a56cffdcd6941d7aa4b1 and index 0
2021-01-08 10:49:18.937 accessor_transaction.go:573 [CRT] BlockChain log: Fetch Cross transaction map[]
2021-01-08 10:49:18.937 estimatefee.go:326 [DBG] Mempool log: Estimate fee register block success for block hash %!!(MISSING)s(uint8=0)%!!(MISSING)(EXTRA string=e24f9c4f7d9fec96bdd4090c7520f45674cc9919b9e0a56cffdcd6941d7aa4b1)
2021-01-08 10:49:18.939 shardprocess.go:199 [INF] BlockChain log: SHARD 0 | Finish Insert new block 3760, with hash e24f9c4f7d9fec96bdd4090c7520f45674cc9919b9e0a56cffdcd6941d7aa4b1 🔗
Syncker Insert 2 shard 0 block(from 3759 to 3760) elaspse 0.012115 
2021-01-08 10:49:18.939 ws_transaction.go:51 [INF] RPC log: Finish Subscribe New Pending Transaction  d04e1c15c090158e31856cec6b4b01851cdeb975ebd77b957922615416867a4a
2021-01-08 10:49:19.037 websocket.go:162 [INF] RPC log: Websocket Connection Closed from client 113.161.55.181:52072 

panic: runtime error: index out of range [4] with length 2

goroutine 313659 [running]:
github.com/incognitochain/incognito-chain/blockchain.(*BlockChain).GetShardBlockByHeight(0xc000ba12c0, 0xeb0, 0x176bb04, 0xc005d87ab0, 0xc006f92fc0, 0x4aef31)
	/home/thach/jenkins/jenkins/workspace/VPS162/this_build_chain/blockchain/accessor_blockchain.go:181 +0x43c
github.com/incognitochain/incognito-chain/rpcserver/rpcservice.BlockService.RetrieveShardBlockByHeight(0xc000ba12c0, 0xc000d52a20, 0x0, 0xc00017d350, 0xeb0, 0x4, 0x2e8fb91, 0x1, 0xc006f93cf0, 0xc000aef7b8, ...)
	/home/thach/jenkins/jenkins/workspace/VPS162/this_build_chain/rpcserver/rpcservice/blockservice.go:198 +0x5c
github.com/incognitochain/incognito-chain/rpcserver.(*HttpServer).handleRetrieveBlockByHeight(0xc000d1d000, 0x175b0c0, 0xc0040427a0, 0xc005f9d260, 0xc000aef828, 0xc001ae3ac0, 0x0)
	/home/thach/jenkins/jenkins/workspace/VPS162/this_build_chain/rpcserver/http_block.go:105 +0x18d
github.com/incognitochain/incognito-chain/rpcserver.(*HttpServer).ProcessRpcRequest(0xc000d1d000, 0x1f16180, 0xc005fa2460, 0xc005a7b500, 0x1)
	/home/thach/jenkins/jenkins/workspace/VPS162/this_build_chain/rpcserver/http.go:313 +0x11ed
github.com/incognitochain/incognito-chain/rpcserver.(*HttpServer).handleRequest.func2(0xc000d1d000, 0x1f16180, 0xc005fa2460, 0xc005a7b500, 0x1970d01, 0xc005f9d200)
	/home/thach/jenkins/jenkins/workspace/VPS162/this_build_chain/rpcserver/http.go:182 +0x52
created by github.com/incognitochain/incognito-chain/rpcserver.(*HttpServer).handleRequest
	/home/thach/jenkins/jenkins/workspace/VPS162/this_build_chain/rpcserver/http.go:181 +0x2e5

```

**Comment by khanhlh-incognito** [comment]
shard 4 not existed.

**Comment by Hangntt15** [comment]
Crash full node too happen when call RPC "getpublickeymining"
