### ISSUE TITLE
[testnet][fullnode] panic: interface conversion: interface {} is []interface {}, not string

### ISSUE THREAD

**Issue by khanhlh-incognito** [incognitochain/incognito-chain#648]
```
panic: interface conversion: interface {} is []interface {}, not string
goroutine 15186371 [running]:
github.com/incognitochain/incognito-chain/rpcserver.(*WsServer).handleSubcribeCrossCustomTokenPrivacyByPrivateKey(0xc000120700, 0x1186fe0, 0xc00911f1a0, 0xc1c91fa738, 0x2, 0xc204598a20, 0xc2045989c0)
	/root/go/src/github.com/incognitochain/incognito-chain/rpcserver/ws_account.go:197 +0x1061
created by github.com/incognitochain/incognito-chain/rpcserver.(*WsServer).subscribe
	/root/go/src/github.com/incognitochain/incognito-chain/rpcserver/websocket.go:227 +0x346
```

**Comment by tuannguyen100** [comment]
input wrong type : private_key

{
"request":{
"jsonrpc":"1.0",
"method":"subcribecrosscustomtokenprivacybyprivatekey",
"params":[
"privatekey"
],
"id":1
},
"subcription":"11",
"type":0,
}
