### ISSUE TITLE
[consensusv2][local] node crash

### ISSUE THREAD

**Issue by khanhlh-incognito** [incognitochain/incognito-chain#861]
```
020-04-16 18:16:25.729 beaconprocess.go:251 [INF] BlockChain log: BEACON | Finish Insert new Beacon Block 19522, with hash 95099f68457fb9748f4244352704f965c88298f43a99605e67b4284dcdff8657
Syncker Insert 1 beacon block (from 19522 to 19522) elaspse 0.006139
2020-04-16 18:16:26.463 server.go:1705 [DBG] Server log: [peerstate] Start Publish SelfPeerState
2020-04-16 18:16:26.463 server.go:1751 [DBG] Server log: [peerstate] PeerID send to Proxy when publish node state QmU5YxKWhuf4Ha89K4kmCxRweLacFXmFAdKE6N2Exfu6Vo
2020-04-16 18:16:26.463 server.go:1755 [DBG] Server log: Publish peerstate
2020-04-16 18:16:26.463 server.go:1317 [DBG] Server log: Push msg to all peers
Syncker: Insert shard 1 from pool 19683
Syncker: Insert beacon from pool 19522
2020-04-16 18:16:29.463 server.go:1705 [DBG] Server log: [peerstate] Start Publish SelfPeerState
2020-04-16 18:16:29.463 server.go:1751 [DBG] Server log: [peerstate] PeerID send to Proxy when publish node state QmU5YxKWhuf4Ha89K4kmCxRweLacFXmFAdKE6N2Exfu6Vo
2020-04-16 18:16:29.463 server.go:1755 [DBG] Server log: Publish peerstate
2020-04-16 18:16:29.463 server.go:1317 [DBG] Server log: Push msg to all peers
2020-04-16 18:16:29.537 server.go:1263 [DBG] Server log: Receive a peerstate START
2020-04-16 18:16:29.537 server.go:1267 [DBG] Server log: Receive a peerstate END
2020-04-16 18:16:29.537 server.go:1263 [DBG] Server log: Receive a peerstate START
2020-04-16 18:16:29.537 server.go:1267 [DBG] Server log: Receive a peerstate END
2020-04-16 18:16:29.538 server.go:1263 [DBG] Server log: Receive a peerstate START
2020-04-16 18:16:29.538 server.go:1267 [DBG] Server log: Receive a peerstate END
2020-04-16 18:16:29.538 server.go:1263 [DBG] Server log: Receive a peerstate START
2020-04-16 18:16:29.538 server.go:1267 [DBG] Server log: Receive a peerstate END
2020-04-16 18:16:29.542 server.go:1263 [DBG] Server log: Receive a peerstate START
2020-04-16 18:16:29.542 server.go:1267 [DBG] Server log: Receive a peerstate END
2020-04-16 18:16:29.542 server.go:1263 [DBG] Server log: Receive a peerstate START
2020-04-16 18:16:29.542 server.go:1267 [DBG] Server log: Receive a peerstate END
2020-04-16 18:16:29.543 server.go:1263 [DBG] Server log: Receive a peerstate START
2020-04-16 18:16:29.543 server.go:1267 [DBG] Server log: Receive a peerstate END
2020-04-16 18:16:29.544 server.go:1263 [DBG] Server log: Receive a peerstate START
2020-04-16 18:16:29.544 server.go:1267 [DBG] Server log: Receive a peerstate END
2020-04-16 18:16:30.085 server.go:1225 [DBG] Server log: Receive a BFTMsg START
2020-04-16 18:16:30.085 server.go:1259 [DBG] Server log: Receive a BFTMsg END
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xe0064e]
goroutine 22094 [running]:
github.com/incognitochain/incognito-chain/consensus.(*Engine).OnBFTMsg(0xc00009e180, 0xc004183f80)
        /home/thach/jenkins/jenkins/workspace/build_chain/consensus/engine.go:187 +0x2e
github.com/incognitochain/incognito-chain/netsync.(*NetSync).handleMessageBFTMsg(0xc00041c810, 0xc004183f80)
        /home/thach/jenkins/jenkins/workspace/build_chain/netsync/netsync.go:334 +0xa5
github.com/incognitochain/incognito-chain/netsync.(*NetSync).messageHandler.func1(0xc00041c810, 0x131db60, 0xc004183f80)
        /home/thach/jenkins/jenkins/workspace/build_chain/netsync/netsync.go:170 +0x130
created by github.com/incognitochain/incognito-chain/netsync.(*NetSync).messageHandler
        /home/thach/jenkins/jenkins/workspace/build_chain/netsync/netsync.go:142 +0x6a
khanhlh@staking-khanhle:~/incognito-bin/consenssusv2$
```

**Comment by khanhlh-incognito** [comment]
fixed
