### ISSUE TITLE
[consensusv2][local] invalid memory address or nil pointer

### ISSUE THREAD

**Issue by khanhlh-incognito** [incognitochain/incognito-chain#874]
```
2020-04-21 21:19:12.111 shardprocess.go:1125 [INF] BlockChain log: SHARD %!!(MISSING)v(MISSING) | 🔎 Remove outdate branch
Debug bestview 62068
debug BackupShardViews 2
2020-04-21 21:19:12.112 shardprocess.go:1157 [INF] BlockChain log: SHARD 1 | 🔎 0 transactions in block height 62068
2020-04-21 21:19:12.112 shardprocess.go:240 [INF] BlockChain log: SHARD 1 | Finish Insert new block 62068, with hash 8884c6d2722d658acb399d444af57a9304c764edab2180dabb15c432e2f73b3d 🔗
2020-04-21 21:19:12.433 engine.go:74 [INF] Consensus log: Node state role: committee chainID: 1
2020-04-21 21:19:12.434 bftactor.go:98 [INF] Consensus log: start bls-bft consensus for chain shard-1
action
2020-04-21 21:19:12.934 bftactor.go:249 [INF] Consensus log: Case: In vote phase
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0xc9c509]
goroutine 1635506 [running]:
github.com/incognitochain/incognito-chain/consensus/blsbft.(*BLSBFT).sendVote(0xc0032c6400, 0xc0067101b0, 0x1)
        /home/thach/jenkins/jenkins/workspace/build_chain/consensus/blsbft/message.go:108 +0x309
github.com/incognitochain/incognito-chain/consensus/blsbft.(*BLSBFT).Start.func1(0xc0032c6400)
        /home/thach/jenkins/jenkins/workspace/build_chain/consensus/blsbft/bftactor.go:251 +0x15f9
created by github.com/incognitochain/incognito-chain/consensus/blsbft.(*BLSBFT).Start
        /home/thach/jenkins/jenkins/workspace/build_chain/consensus/blsbft/bftactor.go:100 +0x397
khanhlh@staking-khanhle:~/incognito-bin/consenssusv2$
```

**Comment by khanhlh-incognito** [comment]
fixed
