### ISSUE TITLE
[consensusv2][bft2] unable to connect to highway v2-newconsensus

### ISSUE THREAD

**Issue by khanhlh-incognito** [incognitochain/incognito-chain#907]
Highway Log:
```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x1180ce3, 0x16)
        /usr/local/go/src/runtime/panic.go:617 +0x72
runtime.sysMap(0xc3a0000000, 0x4000000, 0x20238f8)
        /usr/local/go/src/runtime/mem_linux.go:170 +0xc7
runtime.(*mheap).sysAlloc(0x1ff2100, 0x2000, 0x1ff2110, 0x1)
        /usr/local/go/src/runtime/malloc.go:633 +0x1cd
runtime.(*mheap).grow(0x1ff2100, 0x1, 0x0)
        /usr/local/go/src/runtime/mheap.go:1222 +0x42
runtime.(*mheap).allocSpanLocked(0x1ff2100, 0x1, 0x2023908, 0xc000355180)
        /usr/local/go/src/runtime/mheap.go:1150 +0x37f
runtime.(*mheap).alloc_m(0x1ff2100, 0x1, 0x450041, 0xc39fffd200)
        /usr/local/go/src/runtime/mheap.go:977 +0xc2
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:1048 +0x4c
runtime.systemstack(0x0)
        /usr/local/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1153

goroutine 2549750272 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:311 fp=0xc2ea247678 sp=0xc2ea247670 pc=0x45ce80
runtime.(*mheap).alloc(0x1ff2100, 0x1, 0x10041, 0x0)
        /usr/local/go/src/runtime/mheap.go:1047 +0x8a fp=0xc2ea2476c8 sp=0xc2ea247678 pc=0x4273ca
runtime.(*mcentral).grow(0x1ff34c0, 0x0)
        /usr/local/go/src/runtime/mcentral.go:256 +0x95 fp=0xc2ea247710 sp=0xc2ea2476c8 pc=0x41a315
runtime.(*mcentral).cacheSpan(0x1ff34c0, 0xc78f56)
        /usr/local/go/src/runtime/mcentral.go:106 +0x2ff fp=0xc2ea247770 sp=0xc2ea247710 pc=0x419e1f
runtime.(*mcache).refill(0x7f6c020511f0, 0x41)
        /usr/local/go/src/runtime/mcache.go:135 +0x86 fp=0xc2ea247790 sp=0xc2ea247770 pc=0x4198b6
runtime.(*mcache).nextFree(0x7f6c020511f0, 0x41, 0xc39fffdb00, 0x0, 0xc399cbeba0)
        /usr/local/go/src/runtime/malloc.go:786 +0x88 fp=0xc2ea2477c8 sp=0xc2ea247790 pc=0x40e1d8
runtime.mallocgc(0x480, 0x0, 0x0, 0xf84440)
        /usr/local/go/src/runtime/malloc.go:939 +0x76e fp=0xc2ea247868 sp=0xc2ea2477c8 pc=0x40eaee
runtime.growslice(0xf84440, 0xc39f9b7946, 0x5, 0x5, 0x432, 0x0, 0x0, 0xc2ea247938)
        /usr/local/go/src/runtime/slice.go:175 +0x151 fp=0xc2ea2478d0 sp=0xc2ea247868 pc=0x446401
google.golang.org/grpc/internal/transport.(*http2Server).Write(0xc000744000, 0xc288345c00, 0xc39f9b7946, 0x5, 0x5, 0xc39fffdb00, 0x42d, 0x42d, 0xc39f9b794b, 0x5, ...)
        /home/thach/go/pkg/mod/google.golang.org/grpc@v1.27.1/internal/transport/http2_server.go:919 +0x394 fp=0xc2ea247948 sp=0xc2ea2478d0 pc=0xc67fc4
google.golang.org/grpc.(*serverStream).SendMsg(0xc339c8fbc0, 0x10c5720, 0xc39fffe100, 0x0, 0x0)
        /home/thach/go/pkg/mod/google.golang.org/grpc@v1.27.1/stream.go:1421 +0x22e fp=0xc2ea247a98 sp=0xc2ea247948 pc=0xcf121e
goroutine 1 [select, 5 minutes]:
github.com/incognitochain/go-libp2p-grpc.(*grpcListener).Accept(0xc000660460, 0x12e0760, 0xc000399380, 0x1472120, 0xc2839a9180)
        /home/thach/go/pkg/mod/github.com/incognitochain/go-libp2p-grpc@v0.0.0-20191225095939-98e504cb1c95/listener.go:29 +0xd3
google.golang.org/grpc.(*Server).Serve(0xc000399380, 0x1463280, 0xc000660460, 0x0, 0x0)
        /home/thach/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:597 +0x1f2
github.com/incognitochain/go-libp2p-grpc.(*GRPCProtocol).Serve(0xc0003e7230, 0x2540be400, 0x0)
        /home/thach/go/pkg/mod/github.com/incognitochain/go-libp2p-grpc@v0.0.0-20191225095939-98e504cb1c95/p2pgrpc.go:45 +0xb2
main.main()
        /home/thach/jenkins/jenkins/workspace/APP_build_highway/highway.go:146 +0xffa

goroutine 20 [chan receive, 3693 minutes]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000148a60)
        /home/thach/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.5/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
        /home/thach/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.5/core/tx_cacher.go:55 +0x9f

goroutine 21 [chan receive, 3693 minutes]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000148a60)
        /home/thach/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.5/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
        /home/thach/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.5/core/tx_cacher.go:55 +0x9f

goroutine 22 [chan receive, 3693 minutes]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000148a60)
        /home/thach/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.5/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
        /home/thach/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.5/core/tx_cacher.go:55 +0x9f

goroutine 23 [chan receive, 3693 minutes]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000148a60)
        /home/thach/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.5/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
        /home/thach/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.5/core/tx_cacher.go:55 +0x9f

goroutine 24 [chan receive, 3693 minutes]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000148a60)
        /home/thach/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.5/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
        /home/thach/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.5/core/tx_cacher.go:55 +0x9f

goroutine 25 [chan receive, 3693 minutes]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000148a60)
        /home/thach/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.5/core/tx_cacher.go:63 +0x97
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
        /home/thach/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.5/core/tx_cacher.go:55 +0x9f
```

**Comment by khanhlh-incognito** [comment]
deployment issues: deploy chain without re-deploy highway
